### ISSUE TITLE
[general] Timer CHECKING CHAIN SYNCHRONIZATION raised exception during start: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by boy-good** [NemProject/nem#7]
2019-07-18 05:33:22.310 INFO synchronizing with Node [[c=#86c0e9]nijuichi[/c] <NCZ6YBREMON6BP5X4M7KOMKPV6JW6YY2SHB3RJ7D>] @ [nijuichi.nem.ninja] (org.nem.peer.services.NodeSynchronizer b)
2019-07-18 05:33:22.717 WARNING Timer SYNC raised exception: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
        at org.nem.core.connect.HttpMethodClient.sendRequest(HttpMethodClient.java:118)
        at org.nem.core.connect.HttpMethodClient.post(HttpMethodClient.java:89)
        at org.nem.peer.connect.HttpCommunicator.a(HttpCommunicator.java:37)
        at org.nem.nis.connect.AuditedCommunicator.a(AuditedCommunicator.java:31)
        at org.nem.nis.sz.uht.a(HttpConnector.java:145)
        at org.nem.nis.sz.uht.a(HttpConnector.java:157)
        at org.nem.nis.sz.uht.i(HttpConnector.java:110)
        at org.nem.nis.pz.mtf.fG(RemoteBlockLookupAdapter.java:29)
        at org.nem.nis.sync.BlockChainComparer$Impl.fr(BlockChainComparer.java:94)
        at org.nem.nis.sync.BlockChainComparer$Impl.fp(BlockChainComparer.java:60)
        at org.nem.nis.sync.BlockChainComparer.a(BlockChainComparer.java:32)
        at org.nem.nis.sync.BlockChainUpdater.a(BlockChainUpdater.java:148)
        at org.nem.nis.sync.BlockChainUpdater.c(BlockChainUpdater.java:83)
        at org.nem.nis.BlockChain.b(BlockChain.java:112)
        at org.nem.nis.BlockChain.a(BlockChain.java:104)
        at org.nem.nis.tae.a(CountingBlockSynchronizer.java:39)
        at org.nem.peer.services.NodeSynchronizer.b(NodeSynchronizer.java:50)
        at org.nem.peer.PeerNetwork.gt(PeerNetwork.java:141)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        ... 3 more
 (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)

**Comment by gimre-xymcity** [comment]
@harryweiyongjie @boy-good any of you still have issues?

**Comment by DreamHackchosenone** [comment]
@gimre-xymcity still get this issue
nis-0.6.100.tgz
Ubuntu 20.04.3
